Repository flexycode/CCDATRCL, pull requests merged in 2024-08, with the labels that each got.

#27 ✨ Refactor Array.py
  ProblemSet/Week 2/Problem/Python/Array.py
Labels: enhancement

#29 ✨ Refactor List.py
  ProblemSet/Week 2/Problem/Python/List.py
Labels: documentation, enhancement

#30 ✨ Refactor Stacks.js
  ProblemSet/Week 2/Problem/JavaScript/Stacks.js
Labels: bug, documentation, enhancement

#32 ♻️ Refactor Queue.py
  ProblemSet/Week 2/Problem/Python/Queue.py
Labels: documentation, enhancement

#41 👷 Linked List
  week 2/Module3-Linked Lists.pptx
  week 2/Module3.1-Linked Lists 2.pptx
Labels: documentation
